import fs from 'node:fs';
import path from 'node:path';
import { videoJobsStore } from '@/server/config/videoJobs';
import { storyboardsStore } from '@/server/config/storyboards';
import { productStore } from '@/server/config/products';
import { settingsStore } from '@/server/config/settings';
import { getFontsDir, getVideoLibraryDir, getVideoWorkDir } from '@/server/config/paths';
import { createLogger } from '@/server/utils/logger';
import { generateVoice } from '@/server/ai-services/voiceGenerator';
import { transcribeWordTimestamps } from '@/server/ai-services/transcription';
import { buildSubtitleCues, estimateWordTimings, groupIntoCues } from '@/server/video-engine/subtitleTiming';
import { buildAssSubtitleFile } from '@/server/video-engine/assSubtitles';
import { escapeFilterPath } from '@/server/video-engine/ffmpegExpr';
import { runFfmpeg } from '@/server/video-engine/ffmpeg';
import { computeVoiceConformFactor, conformVoiceToDuration, rescaleWordTimings } from '@/server/video-engine/voiceConform';
import { getVideoProvider } from '@/server/video-engine/videoProviderFactory';
import { sumSceneDurations, DEFAULT_SCENE_DURATION_SECONDS } from '@/lib/storyboards/sceneDuration';
import { buildCombinedVoiceoverScript } from '@/lib/storyboards/voiceoverScript';
import { VIDEO_CANVAS_WIDTH_PX, VIDEO_CANVAS_HEIGHT_PX } from '@/lib/video/constants';
import type { VideoJob, VideoJobStage } from '@/types/domain';

const log = createLogger('videoOrchestrator');

const STAGE_ORDER: VideoJobStage[] = ['keyframes', 'animate', 'voiceover', 'subtitles', 'compose'];
const STAGE_START_PERCENT: Record<VideoJobStage, number> = { keyframes: 5, animate: 15, voiceover: 55, subtitles: 70, compose: 80, done: 100, failed: 0 };

function nowIso(): string {
  return new Date().toISOString();
}

function emitProgress(jobId: string, stage: VideoJobStage, percent: number, message: string): void {
  const job = videoJobsStore.get(jobId);
  if (!job) return;
  videoJobsStore.upsert({ ...job, progress: { stage, percent, message }, updatedAt: nowIso() });
}

/**
 * Kicks off video generation for a Storyboard and returns immediately — the pipeline itself
 * (keyframes already rendered client-side and written to disk by the caller -> animate ->
 * voiceover -> subtitles -> compose) runs for minutes, far longer than this app's other AI calls,
 * so this fires-and-forgets rather than blocking the HTTP request (matching the pre-pivot
 * orchestrator's own `void executeDailyGeneration(...)` pattern). `jobId` is generated by the
 * caller (the /api/videos/generate route), not here — the route needs it up front to know where
 * to write the already-rendered keyframe files before this function ever runs.
 */
export function startVideoGeneration(jobId: string, storyboardId: string, keyframePaths: Record<number, string>): void {
  const now = nowIso();
  videoJobsStore.upsert({
    id: jobId,
    storyboardId,
    status: 'running',
    progress: { stage: 'keyframes', percent: STAGE_START_PERCENT.keyframes, message: 'Saved scene keyframes' },
    createdAt: now,
    updatedAt: now,
  });
  void runVideoJob(jobId, storyboardId, keyframePaths).catch((error) => {
    log.error(`Video job ${jobId} failed outside its own error handling`, error);
  });
}

async function runVideoJob(jobId: string, storyboardId: string, keyframePaths: Record<number, string>): Promise<void> {
  try {
    const storyboard = storyboardsStore.get(storyboardId);
    if (!storyboard) throw new Error(`Storyboard "${storyboardId}" not found`);
    const product = productStore.get(storyboard.productId);
    if (!product) throw new Error(`Product "${storyboard.productId}" not found`);
    if (storyboard.scenes.length === 0) throw new Error('This storyboard has no scenes to render');

    const settings = settingsStore.load();
    const workDir = getVideoWorkDir(jobId);
    const clipsDir = path.join(workDir, 'clips');
    fs.mkdirSync(clipsDir, { recursive: true });

    const totalDurationSeconds = sumSceneDurations(storyboard.scenes);

    // --- Stage: animate ---
    emitProgress(jobId, 'animate', STAGE_START_PERCENT.animate, `Animating scene 1 of ${storyboard.scenes.length}`);
    const provider = getVideoProvider(settings);
    const clipPaths: string[] = [];
    for (let i = 0; i < storyboard.scenes.length; i++) {
      const scene = storyboard.scenes[i]!;
      const imagePath = keyframePaths[scene.number];
      if (!imagePath || !fs.existsSync(imagePath)) throw new Error(`Missing rendered keyframe for scene ${scene.number}`);
      const clipPath = path.join(clipsDir, `scene-${scene.number}.mp4`);
      const durationSeconds = scene.durationSeconds ?? DEFAULT_SCENE_DURATION_SECONDS;
      const { jobId: providerHandle } = await provider.animateImage({ imagePath, motionPrompt: scene.visualDescription, durationSeconds, outputPath: clipPath });
      const result = await provider.checkStatus({ jobId: providerHandle });
      if (result.status === 'failed') throw new Error(`Scene ${scene.number} animation failed: ${result.error}`);
      if (result.status !== 'complete') throw new Error(`Scene ${scene.number} animation did not complete synchronously (provider "${provider.name}" needs polling support)`);
      clipPaths.push(result.videoPath);
      const percentThroughStage = STAGE_START_PERCENT.animate + Math.round(((i + 1) / storyboard.scenes.length) * (STAGE_START_PERCENT.voiceover - STAGE_START_PERCENT.animate));
      emitProgress(jobId, 'animate', percentThroughStage, `Animated scene ${i + 1} of ${storyboard.scenes.length}`);
    }

    // --- Stage: voiceover ---
    emitProgress(jobId, 'voiceover', STAGE_START_PERCENT.voiceover, 'Generating voiceover');
    const script = buildCombinedVoiceoverScript(storyboard.scenes);
    const rawVoicePath = path.join(workDir, 'voice-raw.wav');
    const voice = await generateVoice({
      text: script,
      voice: settings.voicePreset ?? 'warm-female',
      settings,
      outputPath: rawVoicePath,
      targetDurationSeconds: totalDurationSeconds,
    });
    const stretchFactor = computeVoiceConformFactor(voice.durationSeconds, totalDurationSeconds);
    const conformedVoicePath = path.join(workDir, 'voice-conformed.wav');
    if (stretchFactor === 1) {
      fs.copyFileSync(rawVoicePath, conformedVoicePath);
    } else {
      await conformVoiceToDuration(rawVoicePath, totalDurationSeconds, stretchFactor, conformedVoicePath);
    }

    // --- Stage: subtitles ---
    emitProgress(jobId, 'subtitles', STAGE_START_PERCENT.subtitles, 'Aligning subtitles');
    const wordTimestamps = voice.source === 'openai' ? await transcribeWordTimestamps(rawVoicePath, settings) : null;
    const rescaled = wordTimestamps ? rescaleWordTimings(wordTimestamps, stretchFactor) : null;
    const cues = rescaled ? groupIntoCues(rescaled) : buildSubtitleCues(script, estimateWordTimings(script, totalDurationSeconds), totalDurationSeconds);
    const assPath = path.join(workDir, 'subtitles.ass');
    fs.writeFileSync(
      assPath,
      buildAssSubtitleFile(cues, { fontFamily: product.fontFamily ?? 'Inter', colorHex: '#FFFFFF', position: 'bottom', canvasWidth: VIDEO_CANVAS_WIDTH_PX, canvasHeight: VIDEO_CANVAS_HEIGHT_PX }),
      'utf-8',
    );

    // --- Stage: compose ---
    emitProgress(jobId, 'compose', STAGE_START_PERCENT.compose, 'Composing final video');
    const productFolderName = product.name.replace(/[\\/]/g, '-');
    const outputPath = path.join(getVideoLibraryDir(productFolderName), `${jobId}.mp4`);
    const clipInputs = clipPaths.flatMap((p) => ['-i', p]);
    const n = clipPaths.length;
    const concatLabels = Array.from({ length: n }, (_, i) => `[${i}:v]`).join('');
    const filterComplex = `${concatLabels}concat=n=${n}:v=1:a=0[vcat];[vcat]ass=filename=${escapeFilterPath(assPath)}:fontsdir=${escapeFilterPath(getFontsDir())}[vout]`;
    await runFfmpeg(
      [
        ...clipInputs,
        '-i',
        conformedVoicePath,
        '-filter_complex',
        filterComplex,
        '-map',
        '[vout]',
        '-map',
        `${n}:a`,
        '-c:v',
        'libx264',
        '-preset',
        'fast',
        '-crf',
        '18',
        '-pix_fmt',
        'yuv420p',
        '-c:a',
        'aac',
        '-b:a',
        '192k',
        '-ar',
        '44100',
        '-ac',
        '2',
        '-movflags',
        '+faststart',
        outputPath,
      ],
      'compose final video (concat filter, not demuxer)',
    );

    const job = videoJobsStore.get(jobId);
    videoJobsStore.upsert({
      ...(job as VideoJob),
      status: 'complete',
      progress: { stage: 'done', percent: 100, message: 'Complete' },
      videoPath: outputPath,
      durationSeconds: totalDurationSeconds,
      updatedAt: nowIso(),
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    log.error(`Video job ${jobId} failed: ${message}`);
    const job = videoJobsStore.get(jobId);
    if (job) {
      videoJobsStore.upsert({ ...job, status: 'failed', progress: { stage: 'failed', percent: job.progress.percent, message }, error: message, updatedAt: nowIso() });
    }
  }
}

export { STAGE_ORDER };
